baseurl = "https://youngkin.github.io"
title = "Raspberry Pi Programming"
theme = "hugo-theme-cleanwhite-rsy"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
#disqusShortname = ""
#googleAnalytics = ""
#preserveTaxonomyNames = true
paginate = 20 #frontpage pagination
enableRobotsTXT = true
canonifyURLs = true

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

#[outputs]
#home = ["HTML", "RSS", "Algolia"]
#home = ["HTML", "RSS"]
#home = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
[params]
  #header_image = "images/MeAtJackson.jpeg"
  header_image = "images/main_go_wideandtall_darklayer.jpeg"
  logo_image = "images/YBrand_edit.png"
  title = "Learn You Some Raspberry Pi For Great Good!"
  author = "Rich Youngkin"
  description = "How to effectively use a Raspberry Pi for GPIO programming, general software development and as a deployment platform"
  slogan = "GPIO programming, Software Development, and Software Deployment on Raspberry Pis"
  SEOTitle = "Raspberry Pi GPIO Programming and Software Development"
  keyword = "Rich, Youngkin, Raspberry Pi, Docker, Kubernetes, Go, Golang, GPIO, Microservice"
  toc = true
  #page_view_conter = true
 
  # Sidebar settings
  sidebar_about_description = "How to effectively use a Raspberry Pi for GPIO programming, general software development and as a deployment platform"
  sidebar_avatar = "images/MeAtJackson.jpeg" 
  about_me = true

  featured_tags = true 
  featured_condition_size = 2 # How many posts have to have a given tag to be featured (greater-than)

  image_404 = "images/404-bg.jpg"
  title_404 = "We couldn't find what you were looking for..."
  omit_categories = false

  friends = false
  bookmarks = false

  # comments
  hyvor = true
  github = false

  # leancloud storage for page view counter
 # page_view_conter = false 
 # leancloud_app_id = ""
 # leancloud_app_key = ""

  # algolia site search
  #algolia_search = true
  #algolia_appId = ""
  #algolia_indexName = ""
  #algolia_apiKey = ""

  # Include any custom CSS and/or JS files, url or relative to /static folder
  #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

  [params.social]
  rss            = true 
  email          = "rich.youngkin@gmail.com"
  linkedin       = "https://www.linkedin.com/in/richard-youngkin-0749763"
  github         = "https://github.com/youngkin"
  medium         = "https://medium.com/@RichYoungkin"
  stackoverflow  = "https://stackoverflow.com/users/2646870/rich"
  reddit         = "https://www.reddit.com/user/elevation5280"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #instagram     = "full profile url in instagram"
  #twitter        = "https://twitter.com"
  #wechat        = "your wechat qr code image"
  #pinterest     = "full profile url in pinterest"
  #gitlab        = "full profile url in gitlab"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #xing          = "https://www.xing.com/profile/yourxingid"
  #git           = "full profile url for git user"
  
  #[[params.friend_link]]
  #title = "Linda的博客"
  #href =  "https://zhaozhihan.com"

  #[[params.bookmark_link]]
  #title =  "Martin Fowler"
  #href =  "https://martinfowler.com"
  #[[params.bookmark_link]]
  #title = "ServiceMesher"
  #href =  "http://www.servicemesher.com"
  #[[params.bookmark_link]]
  #title =  "Pxhere"
  #href = "https://pxhere.com"
  #[[params.bookmark_link]]
  #title = "unsplash"
  #href = "https://unsplash.com"
  
#[outputFormats.Algolia]
#baseName = "algolia"
#isPlainText = true
#mediaType = "application/json"
#notAlternative = true

#[params.algolia]
#vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
#params = ["categories", "tags"] 

#[markup]
#  [markup.tableOfContents]
#    endLevel = 2
#    startLevel = 1
#  [markup.highlight]
#    style = "dracula"
